version: '3'

volumes:
  api_database: {}

services:
  api:
    image: kk11-api:latest
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 13000:3000
    environment:
      - DATABASE_URL=mysql2://root:root@database/?encoding=utf8mb4&charset=utf8mb4&collation=utf8mb4_general_ci
  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - api_database:/var/lib/mysql
    ports:
      - 13306:3306
