openapi: 3.0.0
info:
  title: kk11
  version: '1.0'
  description: KK11
  license:
    name: MIT
  contact:
    name: windyakin
servers:
  - url: 'http://localhost:13000'
    description: local
paths:
  /v1/authentication:
    post:
      summary: SignUp
      operationId: SignUp
      responses:
        '200':
          description: OK
          headers:
            KK11-Access-Token:
              schema:
                type: string
              required: true
            KK11-Identifier:
              schema:
                type: string
              required: true
            KK11-Token-Type:
              schema:
                type: string
              required: true
            KK11-Client:
              schema:
                type: string
              required: true
            KK11-Token-Expiry:
              schema:
                type: string
              required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    $ref: '#/components/schemas/DeviseSucceedResponseData'
                required:
                  - status
                  - data
              examples:
                signUpResponse:
                  value:
                    status: success
                    data:
                      uid: example@example.com
                      id: 1
                      email: example@example.com
                      provider: email
                      username: example
                      allow_password_change: false
                      created_at: '2020-05-05T00:00:00.000Z'
                      updated_at: '2020-05-05T00:00:00.000Z'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviseErrorResponse'
              examples: {}
      description: Create the account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@example.com
                password:
                  type: string
                  example: password
                  format: password
                password_confirmation:
                  type: string
                  format: password
                  example: password
                username:
                  type: string
                  example: example
              required:
                - email
                - password
                - password_confirmation
                - username
            examples:
              signUpRequest:
                value:
                  username: example
                  email: example@example.com
                  password: password
                  password_confirmation: password
        description: ''
      parameters: []
      security: []
      tags:
        - DeviseOperation
  /v1/authentication/sign_in:
    post:
      summary: ''
      operationId: SignIn
      responses:
        '200':
          description: OK
          headers:
            KK11-Access-Token:
              schema:
                type: string
              required: true
            KK11-Token-Type:
              schema:
                type: string
              required: true
            KK11-Token-Client:
              schema:
                type: string
              required: true
            KK11-Token-Expiry:
              schema:
                type: string
              required: true
            KK11-Token-Identifier:
              schema:
                type: string
              required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/DeviseSucceedResponseData'
              examples:
                SignInResponse:
                  value:
                    data:
                      id: 1
                      email: example@example.com
                      provider: email
                      username: example
                      uid: example@example.com
                      allow_password_change: false
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  errors:
                    type: array
                    items:
                      type: string
              examples:
                example-1:
                  value:
                    success: false
                    errors:
                      - Invalid login credentials. Please try again.
      description: Login and get api access token
      security: []
      tags:
        - DeviseOperation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@example.com
                password:
                  type: string
                  format: password
                  example: password
              required:
                - email
                - password
            examples:
              SinInRequestExample:
                value:
                  email: example@example.com
                  password: password
  /v1/user/items.json:
    get:
      summary: Your GET endpoint
      tags:
        - UserItemOperation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserItemResponse'
                required:
                  - items
              examples: {}
      operationId: GetUserItems
      parameters: []
      description: Get user items
    parameters: []
  /v1/master/books.json:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  books:
                    $ref: '#/components/schemas/MasterBookResponse'
                required:
                  - books
      operationId: get-v1-master-books.json
      description: Get master books
      parameters:
        - schema:
            type: array
          in: query
          name: ids
          required: true
          description: ''
      security: []
  /v1/master/authors.json:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  authors:
                    type: array
                    items:
                      $ref: '#/components/schemas/MasterAuthorResponse'
      operationId: get-v1-master-authors.json
      security: []
      parameters:
        - schema:
            type: integer
          in: query
          name: ids
          description: ''
          required: true
components:
  schemas:
    DeviseErrorResponse:
      title: DeviseErrorResponse
      type: object
      x-examples:
        DeviseErrorResponseExample:
          status: error
          data:
            id: null
            provider: email
            uid: ''
            allow_password_change: false
            username: example
            email: example@example.com
            created_at: null
            updated_at: null
          errors:
            email:
              - has already been taken
            full_messages:
              - Email has already been taken
      properties:
        status:
          type: string
        data:
          type: object
        errors:
          type: object
          properties:
            full_messages:
              type: array
              items:
                type: string
      required:
        - status
    DeviseSucceedResponseData:
      title: DeviseSucceedResponseData
      type: object
      x-examples:
        DeviseSucceedResponseDataExample:
          id: 1
          email: example@example.com
          provider: email
          username: example
          uid: example@example.com
          allow_password_change: false
      properties:
        id:
          type: integer
        email:
          type: string
        provider:
          type: string
        username:
          type: string
        uid:
          type: string
        allow_password_change:
          type: boolean
      required:
        - id
        - email
        - provider
        - username
        - uid
        - allow_password_change
    MasterBookResponse:
      title: MasterBookResponse
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        published_at:
          type: string
          format: date
        coalition:
          type: boolean
        explicit:
          type: boolean
        book_size:
          type: string
          enum:
            - b5
            - b4
            - a5
            - other
        tora_id:
          type:
            - string
            - 'null'
        melon_id:
          type:
            - integer
            - 'null'
        booth_id:
          type:
            - integer
            - 'null'
        authors:
          type: array
          items:
            type: integer
        circles:
          type: array
          items:
            type: integer
      required:
        - id
        - title
        - published_at
        - coalition
        - explicit
        - authors
        - circles
    MasterAuthorResponse:
      title: MasterAuthorResponse
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        name_kana:
          type: string
        description:
          type:
            - string
            - 'null'
        twitter_id:
          type:
            - string
            - 'null'
        pixiv_id:
          type:
            - string
            - 'null'
        website_url:
          type:
            - string
            - 'null'
      required:
        - id
        - name
        - name_kana
        - description
        - twitter_id
        - pixiv_id
        - website_url
    MasterCircleResponse:
      title: MasterCircleResponse
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        name_kana:
          type: string
        description:
          type: string
      required:
        - id
        - name
        - name_kana
        - description
    UserItemResponse:
      title: UserItemResponse
      type: object
      properties:
        id:
          type: string
        master_type:
          type: string
        master_id:
          type: integer
        created_at:
          type: string
          format: time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - master_type
        - master_id
        - created_at
        - updated_at
  securitySchemes:
    KK11-Access-Token:
      type: apiKey
      in: header
      description: ''
      name: KK11-Access-Token
    KK11-Client:
      name: KK11-Client
      type: apiKey
      in: header
    KK11-Identifier:
      name: KK11-Identifier
      type: apiKey
      in: header
security:
  - KK11-Access-Token: []
  - KK11-Client: []
  - KK11-Identifier: []
